name: CMake on a single platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
  nlohmann_json_DIR: ${{ github.workspace }}/vcpkg_installed/x64-windows/share/nlohmann_json

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Install GitVersion
        if: contains(github.ref, 'master')
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        if: contains(github.ref, 'master')
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.1

      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --triplet x64-windows

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022" -T host=x64 -A x64

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Create Installer
        run: makensis.exe ${{ github.workspace }}/installer.nsi

      - name: Add Version to Installer
        if: contains(github.ref, 'master')
        run: mv ClipboardActions.Installer.x64.exe ClipboardActions.Installer.${{ steps.gitversion.outputs.semVer }}.x64.exe

      - name: Upload Installer
        if: contains(github.ref, 'master')
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ClipboardActions.Installer.x64.exe
          path: ClipboardActions.Installer.${{ steps.gitversion.outputs.semVer }}.x64.exe
