name: CMake on a single platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
  nlohmann_json_DIR: ${{ github.workspace }}/vcpkg_installed/x64-windows/share/nlohmann_json

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.1

      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --triplet x64-windows

      - name: Print stuff
        run: ls ${{ github.workspace }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 17 2022" -T host=x64 -A x64

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Create Installer
        run: makensis.exe ${{ github.workspace }}/installer.nsi
